{{- if .Values.snipeit.customStartup.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snipeit.fullname" . }}-entrypoint-override
  labels:
    {{- include "snipeit.labels" . | nindent 4 }}
data:
  startup.sh: |
    #!/bin/sh
    file_env() {
        local var="$1"
        local fileVar="${var}_FILE"
        local def="${2:-}"
        local varValue=$(env | grep -E "^${var}=" | sed -E -e "s/^${var}=//")
        local fileVarValue=$(env | grep -E "^${fileVar}=" | sed -E -e "s/^${fileVar}=//")
        if [ -n "${varValue}" ] && [ -n "${fileVarValue}" ]; then
            echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
            exit 1
        fi
        if [ -n "${varValue}" ]; then
            export "$var"="${varValue}"
        elif [ -n "${fileVarValue}" ]; then
            export "$var"="$(cat "${fileVarValue}")"
        elif [ -n "${def}" ]; then
            export "$var"="$def"
        fi
        unset "$fileVar"
    }

    file_env APP_KEY
    file_env DB_HOST
    file_env DB_PORT
    file_env DB_DATABASE
    file_env DB_USERNAME
    file_env DB_PASSWORD
    file_env REDIS_HOST
    file_env REDIS_PASSWORD
    file_env REDIS_PORT
    file_env MAIL_HOST
    file_env MAIL_PORT
    file_env MAIL_USERNAME
    file_env MAIL_PASSWORD

    if [ -z "$APP_KEY" -a -z "$APP_KEY_FILE" ]; then
      echo "Please re-run this container with an environment variable \$APP_KEY"
      echo "An example APP_KEY you could use is: "
      php artisan key:generate --show
      exit
    fi

    for dir in \
      'data/private_uploads' \
      'data/uploads/accessories' \
      'data/uploads/avatars' \
      'data/uploads/barcodes' \
      'data/uploads/categories' \
      'data/uploads/companies' \
      'data/uploads/components' \
      'data/uploads/consumables' \
      'data/uploads/departments' \
      'data/uploads/locations' \
      'data/uploads/maintenances' \
      'data/uploads/manufacturers' \
      'data/uploads/models' \
      'data/uploads/suppliers' \
      'dumps' \
      'keys'
    do
      [ ! -d "/var/lib/snipeit/$dir" ] && mkdir -p "/var/lib/snipeit/$dir"
    done

    if [ ! -z "${PHP_UPLOAD_LIMIT}" ]; then
        find /etc -type f -name php.ini | while IFS= read -r ini; do
            echo "Changing upload limit to ${PHP_UPLOAD_LIMIT}M in $ini"
            sed -i \
                -e "s/^;\? *upload_max_filesize *=.*/upload_max_filesize = ${PHP_UPLOAD_LIMIT}M/" \
                -e "s/^;\? *post_max_size *=.*/post_max_size = ${PHP_UPLOAD_LIMIT}M/" \
                "$ini"
        done
    fi

    if [ ! -f "/var/www/html/database/migrations/*create_oauth*" ]; then
      cp -a /var/www/html/vendor/laravel/passport/database/migrations/* /var/www/html/database/migrations/
    fi

    if [ "${SESSION_DRIVER}" == "database" ]; then
      cp -a /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Console/stubs/database.stub /var/www/html/database/migrations/2021_05_06_0000_create_sessions_table.php
    fi

    php artisan migrate --force
    php artisan config:clear
    php artisan config:cache
    touch /var/www/html/storage/logs/laravel.log

    export APACHE_LOG_DIR=/var/log/apache2
    exec httpd -DNO_DETACH < /dev/null
{{- end }}
