{{- if .Values.httpRoute.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "snipeit.fullname" . }}
  labels:
    {{- include "snipeit.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "snipeit.fullname" $ }}
          port: {{ .Values.service.port }}
          weight: 1
      matches:
      {{- with .Values.httpRoute.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
