apiVersion: v2
name: mumble
description: A Helm chart for providing mumble server to kubernetes

home: https://github.com/Syntax3rror404/helm-charts
icon: https://raw.githubusercontent.com/mumble-voip/mumble/master/icons/mumble.svg

type: application
version: 1.0.4
appVersion: "v1.6.870" # renovate: datasource=docker depName=ghcr.io/mumble-voip/mumble-server

keywords:
  - mumble
  - voip

sources:
  - https://github.com/mumble-voip/mumble-docker
