apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teamspeak.fullname" . }}-server
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "teamspeak.fullname" . }}-server
  replicas: 1
  selector:
    matchLabels:
      {{- include "teamspeak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "teamspeak.selectorLabels" . | nindent 8 }}
    spec:
      # Pod security context – applies to all containers in the pod
      securityContext:
        {{- toYaml .Values.teamspeak.podSecurityContext | nindent 8 }}
      containers:
        - name: teamspeak-server
          # Container-specific security context
          securityContext:
            {{- toYaml .Values.teamspeak.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.teamspeak.image }}:{{ .Values.teamspeak.tag }}"
          ports:
            - containerPort: {{ .Values.teamspeak.ports.udp }}
              protocol: UDP
            {{- range .Values.teamspeak.ports.tcp }}
            - containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          env:
            - name: TS3SERVER_LICENSE
              value: {{ .Values.teamspeak.licenseAccept | quote }}
            - name: TS3SERVER_DB_PLUGIN
              value: "ts3db_mariadb"
            - name: TS3SERVER_DB_SQLCREATEPATH
              value: "create_mariadb"
            - name: TS3SERVER_DB_HOST
              value: "{{ .Values.mariadbOperator.useExisting.mariaDbRef }}-internal.{{ .Values.mariadbOperator.useExisting.namespace }}.svc"
            - name: TS3SERVER_DB_USER
              value: "{{ .Values.mariadbOperator.username }}"
            - name: TS3SERVER_DB_PASSWORD
              value: "{{ .Values.mariadbOperator.password }}"
            - name: TS3SERVER_DB_NAME
              value: "{{ .Values.mariadbOperator.database }}"
            - name: TS3SERVER_DB_WAITUNTILREADY
              value: "30"
          volumeMounts:
            - name: data
              mountPath: /var/ts3server
            # Additional volume for the runtime directory (fixes permission issue)
            - name: run-ts3server
              mountPath: /var/run/ts3server
          resources:
            {{- toYaml .Values.teamspeak.resources | nindent 12 }}
      volumes:
        # Always provide an emptyDir for /var/run/ts3server
        - name: run-ts3server
          emptyDir: {}
        # Data volume is only defined as emptyDir if persistence is disabled
        # (otherwise it comes from volumeClaimTemplates)
        {{- if not .Values.teamspeak.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
  {{- if .Values.teamspeak.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "teamspeak.selectorLabels" . | nindent 10 }}
          {{- with .Values.customLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.teamspeak.persistence.accessModes | nindent 10 }}
        {{- if .Values.teamspeak.persistence.storageClass }}
        storageClassName: {{ .Values.teamspeak.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.teamspeak.persistence.size | quote }}
  {{- end }}