---
{{- if and .Values.rcon.enabled (not .Values.existingRconSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft.fullname" . }}-rcon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
type: Opaque
stringData:
  rcon-password: {{ .Values.rcon.password | quote }}
{{- end }}
