---
apiVersion: v2
name: minecraft
description: A Helm chart for a Minecraft Java Edition Server on Kubernetes
type: application
version: 1.1.2
appVersion: "1.21.1"
keywords:
  - minecraft
  - java
  - game-server
  - modded
  - neoforge
