---
apiVersion: v2
name: minecraft
description: Helm chart for neoforge (modded) or vanilla Minecraft Java Server
type: application
version: 1.1.16
appVersion: "1.21.1"
keywords:
  - minecraft
  - java
  - game-server
  - modded
  - neoforge
