---
apiVersion: v2
name: minecraft
description: Minecraft Java neoforge (modded) and vanilla server with autoupdate and installation support
type: application
version: 1.2.20
appVersion: "1.21.1"
icon: https://upload.wikimedia.org/wikipedia/en/b/be/Minecraft_game_logo_2023.png
keywords:
  - minecraft
  - java
  - game-server
  - modded
  - neoforge
