{{- if .Values.adminHttpRoute.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  {{- with .Values.adminHttpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.adminHttpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.adminHttpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "keycloak.fullname" $ }}
          port: {{ .Values.service.port }}
          weight: 1
      {{- with .Values.adminHttpRoute.matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
