name: Release Charts

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        id: release
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .
          pages_branch: master
          pages_index_path: charts/index.yaml
          packages_with_index: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to OCI
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          REGISTRY="oci://ghcr.io/${OWNER,,}/helm-charts"
          for tgz in charts/*.tgz; do
            filename=$(basename "$tgz" .tgz)
            chart_name=$(echo "$filename" | sed 's/-[0-9].*//')
            chart_version=$(echo "$filename" | sed 's/.*-\([0-9].*\)/\1/')
            if helm show chart "${REGISTRY}/${chart_name}" --version "$chart_version" &>/dev/null; then
              echo "Skip ${chart_name}:${chart_version} (already in registry)"
              continue
            fi
            echo "Pushing ${chart_name}:${chart_version}"
            helm push "$tgz" "${REGISTRY}"
          done
