name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: helm/chart-releaser-action@v1.6.0
        id: release
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .
          pages_branch: master
          pages_index_path: charts/index.yaml
          packages_with_index: true

      - name: Login to GHCR
        if: hashFiles('.cr-release-packages/*.tgz') != ''
        run: helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push to OCI
        if: hashFiles('.cr-release-packages/*.tgz') != ''
        run: |
          for chart in .cr-release-packages/*.tgz; do
            helm push "$chart" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
          done
